### ISSUE TITLE
Implement missing beanstalk commands

### ISSUE THREAD

**Issue by edqallen** [getjackd/jackd#23]
Are there any plans to implement all (or some) of the missing commands from the beanstalk protocol?  I'm migrating a project to node from PHP and have discovered that the protocol implementation in jackd appears to be incomplete.  In particular I'm looking for the stats commands `stats-job`, `stats-tube`, and `stats`.

TIA, and great work on the project so far.

**Comment by ruffrey** [comment]
The project has been really good about accepting PRs so far :) (don't forget TS defs)

I see the stats commands [require outputting yaml](https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L565), which may be the reason they're avoided. Adding a pure JS yaml parser would be my vote. [js-yaml](https://www.npmjs.com/package/js-yaml)

**Comment by divmgl** [comment]
Hey @edqallen! Sorry for the delayed response! I realize this is late but maybe someone else will find this in the future.

@ruffrey is correct: I've left out those commands from `jackd` because one of the core design principles of `jackd` is that it has little to no dependencies. Having to parse YAML would mean bringing in a YAML parser, which I want to avoid doing. [Here's some documentation on it](https://github.com/getjackd/jackd#executing-arbitrary-commands):

> jackd only has first-class support for commands that do not return YAML. 

That being said, you can implement these commands in your own project fairly seamlessly. Here's some code that I'm writing on the fly and is not tested at all, but should give you an idea of how to do this:

```
const YAML = require('yaml')

function stats(conn) {
  const stats = await conn.executeMultiPartCommand('stats\r\n')
  const { 'total-jobs': totalJobs } = YAML.parse(stats)
  return {
    totalJobs
  }
}
```

**Comment by edqallen** [comment]
Thanks, I did do that, but it turned out to be a little more complex if I recall.  I'll look into it after the update for the other issue is in; I put stats, statsJob, and statsTube into my fork of the project since I'd already been "forced" to make one to clear up the ascii problem.

**Comment by divmgl** [comment]
@edqallen I gave this some thought after making a Golang library. I'll be adding support for all of the missing commands. Thanks for creating this issue @edqallen

**Comment by edqallen** [comment]
That's great to hear @divmgl , I'll put the new version through it's paces as soon as it's available.  Thanks!

**Comment by divmgl** [comment]
> That's great to hear @divmgl , I'll put the new version through it's paces as soon as it's available. Thanks!

It's up! https://github.com/getjackd/jackd/releases/tag/v2.1.0

Cheers!
